Repository crosswaves/cross_wave, pull requests merged in 2024-05, with the labels that each got.

#52 feat: profile 파이어베이스 연동
  lib/data/domain/model/profile.dart
  lib/main.dart
  lib/presentation/screen/home_screen.dart
  lib/utils/firebase_store.dart
Labels: SERVER

#61 [SERVER] intro에서 name 파라미터 데이터 넘겨주는 메서드 수정
  lib/main.dart
  lib/presentation/screen/intro_level_screen.dart
  lib/presentation/screen/intro_name_screen.dart
Labels: SERVER

#63 [UI] home, speak 화면 리팩토링
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/select_theme_screen.dart
Labels: UI

#66 feat: api_stt 기능 설정
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/api_file/constants/themes.dart
  lib/api_file/models/chat_model.dart
  lib/api_file/providers/active_theme_provider.dart
  lib/api_file/providers/chats_provider.dart
  lib/api_file/services/ai_handler.dart
  lib/api_file/services/voice_handler.dart
  lib/api_file/widgets/chat_item.dart
  lib/api_file/widgets/my_app_bar.dart
  lib/api_file/widgets/text_and_voice_field.dart
  lib/api_file/widgets/theme_switch.dart
  lib/api_file/widgets/toggle_button.dart
  lib/main.dart
  lib/presentation/screen/talk_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: FC

#69 [SERVER] 주제 선택 후 파이어베이스에 저장 하는 메서드 구현
  lib/data/domain/model/profile.dart
  lib/main.dart
  lib/presentation/components/select_theme_card.dart
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/intro_level_screen.dart
  lib/presentation/screen/intro_name_screen.dart
  lib/presentation/screen/select_theme_screen.dart
  lib/utils/firebase_service.dart
  lib/utils/firebase_store.dart
Labels: SERVER

#77 feat: flutter tts 3.8.1 ver setting
  android/app/src/main/AndroidManifest.xml
  lib/api_file/services/voice_handler.dart
  lib/api_file/widgets/text_and_voice_field.dart
  pubspec.lock
  pubspec.yaml
Labels: FC

#82 feat: bottom 네비바 작업
  lib/presentation/screen/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: UI

#84 feat: 현재 week의 요일별 발화횟수 그래프 작성
  lib/data/repository/conversation_history_load_impl.dart
  lib/data/repository/weekely_message_counter_impl.dart
  lib/domain/repository/weekely_message_counter.dart
  lib/presentation/components/achieve_bar_chart.dart
  lib/presentation/resources/app_colors.dart
  lib/presentation/screen/home_screen.dart
  lib/utils/extensions/color_extensions.dart
Labels: FC

#87 [UI] 홈 화면 구조 변경, 다크테마 적용, 코드 수정
  assets/gold.png
  assets/iron.png
  assets/silver.png
  lib/api_file/constants/themes.dart
  lib/main.dart
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/info_screen.dart
  lib/presentation/screen/select_theme_screen.dart
  lib/theme.dart
  pubspec.yaml
Labels: UI

#89 feat: 저장된 대화내역에 대한 피드백
  lib/domain/model/ai_feedback.dart
  lib/presentation/screen/talk_feedback_screen.dart
Labels: FC

#92 fix: 그래프 bug 수정
  lib/presentation/components/achieve_bar_chart.dart
Labels: UI

#93 [UI] 홈, 인포 스크린 UI 변경 및 수정
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/info_screen.dart
  lib/presentation/screen/select_theme_screen.dart
Labels: UI

#97 feat: 개인정보처리약관 화면 작성
  assets/privacy_policy.md
  lib/presentation/screen/info_screen.dart
  lib/presentation/screen/privacy_policy_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: UI

#99 [FC] 사용자가 선택한 관심있는 주제에 따라 AI 첫 대화 메시지 작성
  lib/api_file/services/ai_handler.dart
  lib/api_file/widgets/text_and_voice_field.dart
  lib/main.dart
  lib/presentation/screen/login_screen.dart
  lib/presentation/screen/select_theme_screen.dart
  lib/utils/firebase_store.dart
Labels: FC

#101 feat: 파이어베이스 로그인 정보 저장
  lib/main.dart
  lib/utils/firebase_service.dart
  lib/utils/firebase_store.dart
  pubspec.lock
Labels: FC

#102 feat: 사용자의 ai 채팅 잔여횟수 갱신
  lib/api_file/widgets/text_and_voice_field.dart
  lib/before_file/home_and_talk/home.dart
  lib/before_file/home_and_talk/login.dart
Labels: FC

#104 [FC] 홈화면 lottie 이미지 추가, 주제 선택 영문화, 대화화면 아바타 -> 프로필사진으로 변경
  assets/computer.png
  assets/lottie/lottie_welcome.json
  lib/api_file/widgets/chat_item.dart
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/select_theme_screen.dart
  lib/presentation/screen/talk_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: FC

#109 feat: y-axis 조정 기능 구현
  lib/presentation/components/achieve_bar_chart.dart
Labels: UI

#110 feat: 구글 로그인 신규/기존 사용자 구별
  lib/presentation/screen/login_screen.dart
  lib/utils/firebase_service.dart
  pubspec.lock
Labels: bug

#111 feat: 대화 화면에서 번역 스크립트 제공
  lib/api_file/widgets/my_app_bar.dart
  lib/domain/model/ai_translate.dart
  lib/presentation/screen/talk_screen.dart
  pubspec.lock
Labels: FC

#115 [BUG] 화면 animation, 바텀네비게이션이미지, 라이선스, Info화면 버그 수정 등
  lib/api_file/widgets/chat_item.dart
  lib/api_file/widgets/my_app_bar.dart
  lib/main.dart
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/info_screen.dart
  lib/presentation/screen/license.dart
  lib/utils/firebase_service.dart
Labels: bug, UI

#119 [FC] Info화면 회원탈퇴, 요금제 메서드 구현
  lib/presentation/screen/info_screen.dart
Labels: FC
