Repository crosswaves/cross_wave, pull requests merged in 2024-04, with the labels that each got.

#6 Feat/UI last lesson
  lib/presentation/components/last_lesson_detail_widget.dart
  lib/presentation/components/last_lesson_widget.dart
  lib/presentation/components/payment_widget.dart
  lib/presentation/profile_screen.dart
Labels: UI

#7 feat: profile_screen 생성
  lib/presentation/profile_screen.dart
Labels: UI

#8 feat : 홈 화면 / 대화 화면
  assets/logo.png
  assets/user.jpg
  lib/home_and_talk/home.dart
  lib/home_and_talk/more_info.dart
  lib/home_and_talk/profile_screen.dart
  lib/home_and_talk/talk.dart
  lib/main.dart
  pubspec.yaml
  test/widget_test.dart
Labels: UI

#20 refator: home_screen
  lib/presentation/screen/home_screen.dart
Labels: UI

#22 refactor: 파일명 수정, 앱바 수정
  lib/data/domain/model/conversation.dart
  lib/presentation/components/conversation_card.dart
  lib/presentation/components/conversation_list.dart
  lib/presentation/components/feedback_popup.dart
  lib/presentation/screen/talk_archive_screen.dart
  lib/presentation/screen/talk_feedback_screen.dart
  lib/presentation/screen/talk_history_screen.dart
Labels: UI

#29 feat: 로그아웃 로직
  lib/presentation/screen/home_screen.dart
  lib/presentation/screen/info_screen.dart
  lib/presentation/screen/z_speak_screen.dart
Labels: FC

#33 refactor: Speak BottomNavigation 경로 수정
  lib/presentation/screen/home_screen.dart
Labels: UI

#41 fix: MaterialPageRoute 수정하여 화면 간 연결 버그 수정
  lib/presentation/screen/talk_archive_screen.dart
  lib/presentation/screen/talk_feedback_screen.dart
  lib/presentation/screen/talk_history_screen.dart
Labels: bug, UI

#43 feat: 인트로 UI 수정
  lib/main.dart
  lib/presentation/screen/intro_level_screen.dart
  lib/presentation/screen/intro_name_screen.dart
  lib/presentation/screen/login_screen.dart
Labels: UI
